// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.MyDbContext;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20251202123755_ConvertReviewProcessToDynamic")]
    partial class ConvertReviewProcessToDynamic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Common.Models.Permissions", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PermissionId");

                    b.HasIndex("PermissionName")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            PermissionName = "todo_create"
                        },
                        new
                        {
                            PermissionId = 2,
                            PermissionName = "todo_review_level1"
                        },
                        new
                        {
                            PermissionId = 3,
                            PermissionName = "todo_review_level2"
                        },
                        new
                        {
                            PermissionId = 4,
                            PermissionName = "admin_manage"
                        });
                });

            modelBuilder.Entity("Common.Models.ReviewStage", b =>
                {
                    b.Property<int>("StageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StageId"));

                    b.Property<int>("RequiredRoleId")
                        .HasColumnType("int");

                    b.Property<int>("SpecificReviewerUserId")
                        .HasColumnType("int");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("StageOrder")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("StageId");

                    b.HasIndex("RequiredRoleId")
                        .HasDatabaseName("IX_ReviewStages_RequiredRoleId");

                    b.HasIndex("SpecificReviewerUserId")
                        .HasDatabaseName("IX_ReviewStages_SpecificReviewerUserId");

                    b.HasIndex("TemplateId", "StageOrder")
                        .IsUnique()
                        .HasDatabaseName("IX_ReviewStages_TemplateId_StageOrder");

                    b.ToTable("ReviewStages");
                });

            modelBuilder.Entity("Common.Models.ReviewTemplate", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TemplateId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TemplateName")
                        .IsUnique()
                        .HasDatabaseName("IX_ReviewTemplates_TemplateName");

                    b.ToTable("ReviewTemplates");
                });

            modelBuilder.Entity("Common.Models.Reviews", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ReviewedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("ReviewerUserId")
                        .HasColumnType("int");

                    b.Property<int?>("StageId")
                        .HasColumnType("int");

                    b.Property<int?>("StageTransitionTransitionId")
                        .HasColumnType("int");

                    b.Property<int>("TodoId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("ReviewedAt")
                        .HasDatabaseName("IX_Reviews_ReviewedAt");

                    b.HasIndex("ReviewerUserId")
                        .HasDatabaseName("IX_Reviews_ReviewerUserId");

                    b.HasIndex("StageId")
                        .HasDatabaseName("IX_Reviews_StageId");

                    b.HasIndex("StageTransitionTransitionId");

                    b.HasIndex("TodoId")
                        .HasDatabaseName("IX_Reviews_TodoId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Common.Models.Roles", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "員工"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "資深員工"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "主管"
                        },
                        new
                        {
                            RoleId = 4,
                            RoleName = "管理員"
                        });
                });

            modelBuilder.Entity("Common.Models.Roles_Permissions", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("Roles_Permissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 4
                        });
                });

            modelBuilder.Entity("Common.Models.StageTransition", b =>
                {
                    b.Property<int>("TransitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransitionId"));

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("NextStageId")
                        .HasColumnType("int");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.HasKey("TransitionId");

                    b.HasIndex("NextStageId")
                        .HasDatabaseName("IX_StageTransitions_NextStageId");

                    b.HasIndex("StageId", "ActionName")
                        .IsUnique()
                        .HasDatabaseName("IX_StageTransitions_StageId_ActionName");

                    b.ToTable("StageTransitions");
                });

            modelBuilder.Entity("Common.Models.TodoLists", b =>
                {
                    b.Property<int>("TodoListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TodoListId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentReviewerUserId")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentStageId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TodoListId");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("IX_TodoLists_CreatedByUserId");

                    b.HasIndex("CurrentReviewerUserId")
                        .HasDatabaseName("IX_TodoLists_CurrentReviewerUserId");

                    b.HasIndex("CurrentStageId")
                        .HasDatabaseName("IX_TodoLists_CurrentStageId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_TodoLists_Status");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("IX_TodoLists_TemplateId");

                    b.ToTable("TodoLists");
                });

            modelBuilder.Entity("Common.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 101,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 102,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 103,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 104,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 105,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 106,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Common.Models.Users_Roles", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users_Roles");

                    b.HasData(
                        new
                        {
                            UserId = 101,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 102,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 103,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 104,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 105,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 106,
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("Common.Models.ReviewStage", b =>
                {
                    b.HasOne("Common.Models.Roles", "RequiredRole")
                        .WithMany()
                        .HasForeignKey("RequiredRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Common.Models.Users", "SpecificReviewerUser")
                        .WithMany()
                        .HasForeignKey("SpecificReviewerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Common.Models.ReviewTemplate", "ReviewTemplate")
                        .WithMany("ReviewStages")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequiredRole");

                    b.Navigation("ReviewTemplate");

                    b.Navigation("SpecificReviewerUser");
                });

            modelBuilder.Entity("Common.Models.ReviewTemplate", b =>
                {
                    b.HasOne("Common.Models.Users", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Common.Models.Reviews", b =>
                {
                    b.HasOne("Common.Models.Users", "ReviewerUser")
                        .WithMany()
                        .HasForeignKey("ReviewerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Common.Models.ReviewStage", "ReviewStage")
                        .WithMany("Reviews")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Common.Models.StageTransition", null)
                        .WithMany("Reviews")
                        .HasForeignKey("StageTransitionTransitionId");

                    b.HasOne("Common.Models.TodoLists", "Todo")
                        .WithMany()
                        .HasForeignKey("TodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReviewStage");

                    b.Navigation("ReviewerUser");

                    b.Navigation("Todo");
                });

            modelBuilder.Entity("Common.Models.Roles_Permissions", b =>
                {
                    b.HasOne("Common.Models.Permissions", "Permission")
                        .WithMany("Roles_Permissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Models.Roles", "Role")
                        .WithMany("Roles_Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Common.Models.StageTransition", b =>
                {
                    b.HasOne("Common.Models.ReviewStage", "ToStage")
                        .WithMany("ToStageTransitions")
                        .HasForeignKey("NextStageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Common.Models.ReviewStage", "FromStage")
                        .WithMany("FromStageTransitions")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FromStage");

                    b.Navigation("ToStage");
                });

            modelBuilder.Entity("Common.Models.TodoLists", b =>
                {
                    b.HasOne("Common.Models.Users", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Common.Models.Users", "CurrentReviewerUser")
                        .WithMany()
                        .HasForeignKey("CurrentReviewerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Common.Models.ReviewStage", "CurrentStage")
                        .WithMany("TodoLists")
                        .HasForeignKey("CurrentStageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Common.Models.ReviewTemplate", "ReviewTemplate")
                        .WithMany("TodoLists")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByUser");

                    b.Navigation("CurrentReviewerUser");

                    b.Navigation("CurrentStage");

                    b.Navigation("ReviewTemplate");
                });

            modelBuilder.Entity("Common.Models.Users_Roles", b =>
                {
                    b.HasOne("Common.Models.Roles", "Role")
                        .WithMany("Users_Roles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Models.Users", "User")
                        .WithMany("Users_Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Common.Models.Permissions", b =>
                {
                    b.Navigation("Roles_Permissions");
                });

            modelBuilder.Entity("Common.Models.ReviewStage", b =>
                {
                    b.Navigation("FromStageTransitions");

                    b.Navigation("Reviews");

                    b.Navigation("ToStageTransitions");

                    b.Navigation("TodoLists");
                });

            modelBuilder.Entity("Common.Models.ReviewTemplate", b =>
                {
                    b.Navigation("ReviewStages");

                    b.Navigation("TodoLists");
                });

            modelBuilder.Entity("Common.Models.Roles", b =>
                {
                    b.Navigation("Roles_Permissions");

                    b.Navigation("Users_Roles");
                });

            modelBuilder.Entity("Common.Models.StageTransition", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Common.Models.Users", b =>
                {
                    b.Navigation("Users_Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
